/**
 * Site Configuration Template
 * 
 * Modify these values to create a new branded site.
 * After modification, you can run the AI regeneration tool to automatically
 * rephrase all wordings while keeping the same themes and structure.
 */

export const siteConfig = {
  // Company Information
  company: {
    name: "My Trip Online",
    legalName: "My Trip Online",
    phone: "+33 1 85 09 83 67",
    email: "contact@my-trip-online.com",
    address: "Paris, France",
  },

  // Domain Configuration
  domains: {
    main: "my-trip-online.com",
    fastTrack: "https://fast-track.my-trip-online.com",
    checkIn: "https://checkin.my-trip-online.com",
  },

  // Brand Colors (HSL format)
  colors: {
    primary: "205 85% 45%",      // Ocean blue
    primaryLight: "205 75% 65%",
    primaryDark: "205 85% 35%",
    accent: "42 95% 55%",         // Gold
    secondary: "210 15% 96%",
  },

  // Pricing Plans
  pricing: {
    medium: {
      id: "medium",
      name: "Medium",
      price: 49,
      period: "Every 3 months",
      description: "Smart travel, frequent and hassle-free",
      features: [
        "Up to 2 free Fast-Track accesses per month",
        "Automated check-in included",
        "Priority entry to selected museums",
      ],
    },
    premium: {
      id: "premium",
      name: "Premium",
      price: 79,
      period: "Every 3 months",
      description: "",
      features: [
        "Up to 5 free Fast-Track accesses per month",
        "Unlimited automated check-ins",
        "Unlimited skip-the-line museum entries",
        "Exclusive discounts on airport lounges",
      ],
    },
  },

  // Content & Wordings (These will be regenerated by AI)
  content: {
    hero: {
      title: "Your one-stop solution for stress-free travel",
      subtitle: "Check-in, Fast-track, museums, and beyond",
      cta: "Explore",
    },
    services: {
      fastTrack: {
        title: "Fast-Track",
        description: "No more endless lines at the airport. Get through security in minutes and enjoy priority access at participating terminals worldwide.",
      },
      checkIn: {
        title: "Automated Check-In",
        description: "Forget manually checking in for your flights. We handle it automatically as soon as online check-in opens, ensuring you get the best seats.",
      },
      museums: {
        title: "Skip-the-Line Museums",
        description: "Don't waste precious vacation time in queues. Gain instant access to world-famous museums and attractions with our skip-the-line passes.",
      },
    },
    whyChooseUs: {
      title: "Why Choose Us",
      reasons: [
        {
          title: "Comprehensive Service",
          description: "From check-in to security, we've got you covered.",
        },
        {
          title: "Global Coverage",
          description: "Access premium services at airports and museums worldwide.",
        },
        {
          title: "Easy Subscription",
          description: "One subscription for multiple benefits.",
        },
      ],
    },
  },

  // SEO
  seo: {
    defaultTitle: "My Trip Online - Stress-Free Travel Solutions",
    defaultDescription: "Fast-track airport security, automated check-in, and skip-the-line museum access. Your complete travel companion.",
    keywords: ["travel", "fast-track", "check-in", "museums", "airport"],
  },

  // Social Links
  social: {
    facebook: "",
    twitter: "",
    instagram: "",
    linkedin: "",
  },
};

export type SiteConfig = typeof siteConfig;
