/**
 * Site Configuration Template
 * 
 * Modify these values to create a new branded site.
 * After modification, you can run the AI regeneration tool to automatically
 * rephrase all wordings while keeping the same themes and structure.
 */

export const siteConfig = {
  // Company Information
  company: {
    name: "Travel Synch",
    legalName: "BLOOMBACK LIMITED",
    phone: "+44 203 936 0018",
    email: "contact@travel-synch.com",
    address: "Office 6, Suite A 13 Reeves Way, South Woodham Ferrers, Chelmsford, Essex, CM3 5XF, United Kingdom",
  },

  // Domain Configuration
  domains: {
    main: "travel-synch.com",
    fastTrack: "https://fast-track.travel-synch.com",
    checkIn: "https://checkin.travel-synch.com",
  },

  // Brand Colors (HSL format)
  colors: {
    primary: "220 70% 25%",      // Deep navy
    primaryLight: "220 60% 45%",
    primaryDark: "220 80% 20%",
    accent: "14 90% 60%",         // Coral orange
    secondary: "220 15% 96%",
  },

  // Pricing Plans
  pricing: {
    medium: {
      id: "medium",
      name: "Medium",
      price: 49,
      period: "Every 3 months",
      description: "Smart travel, frequent and hassle-free",
      features: [
        "Up to 2 free Fast-Track accesses per month",
        "Automated check-in included",
        "Priority entry to selected museums",
      ],
    },
    premium: {
      id: "premium",
      name: "Premium",
      price: 79,
      period: "Every 3 months",
      description: "",
      features: [
        "Up to 5 free Fast-Track accesses per month",
        "Unlimited automated check-ins",
        "Unlimited skip-the-line museum entries",
        "Exclusive discounts on airport lounges",
      ],
    },
  },

  // Content & Wordings (These will be regenerated by AI)
  content: {
    hero: {
      title: "Seamlessly synchronize your entire travel experience",
      subtitle: "Fast-track, automated check-in, museums, and more",
      cta: "Get Started",
    },
    services: {
      fastTrack: {
        title: "Fast-Track Access",
        description: "Skip the airport queues and breeze through security checkpoints. Our fast-track service provides you with priority access at terminals across the globe.",
      },
      checkIn: {
        title: "Smart Check-In",
        description: "Say goodbye to manual check-ins. Our automated system handles your flight check-in the moment it opens, securing optimal seating for you.",
      },
      museums: {
        title: "Priority Museum Entry",
        description: "Maximize your vacation time with instant museum access. Skip lengthy queues and enjoy priority entry to renowned attractions worldwide.",
      },
    },
    whyChooseUs: {
      title: "Why Travel Synch",
      reasons: [
        {
          title: "All-in-One Solution",
          description: "Complete travel services from departure to arrival.",
        },
        {
          title: "Worldwide Access",
          description: "Premium services available at airports and attractions globally.",
        },
        {
          title: "Simple Subscription",
          description: "Single membership unlocking multiple travel benefits.",
        },
      ],
    },
  },

  // SEO
  seo: {
    defaultTitle: "Travel Synch - Synchronized Travel Solutions",
    defaultDescription: "Priority airport fast-track, automated flight check-in, and skip-the-line museum entry. Your synchronized travel companion.",
    keywords: ["travel", "fast-track", "check-in", "museums", "airport", "travel synch"],
  },

  // Social Links
  social: {
    facebook: "",
    twitter: "",
    instagram: "",
    linkedin: "",
  },
};

export type SiteConfig = typeof siteConfig;
